language: go

go:
  - "1.12.x"

# Enabling modules support
env:
  - GO111MODULE=on

# persistent file installation
install: true

before_install:
  - cp .netrc ~/.netrc
  - chmod 600 ~/.netrc

script:
  - make lint
  - make test_unit