version: "3"
services: 
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grahpql
    volumes: 
      - grahpql:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d
  
  #pgadmin
  pgadmin:
    image: dockage/phppgadmin
    environment: 
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=grahpql
    ports: 
      - "3001:80"

  code:
    image: codercom/code-server:v2
    ports:
      - "3030:8080"
    volumes:
      #- "./:/home/coder/.local/share/code-server"
      - "./:/home/coder/project"


volumes: 
  grahpql: